name: Build and Test

on:
    workflow_call:

jobs:
    build_test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup NodeJs
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: Install client dependencies
              working-directory: ./
              run: yarn install
            - name: Client tests lint
              run: yarn run lint
            - name: Generate build
              run: npm run build
            # Share artifact inside workflow
            - name: Share artifact inside workflow
              if: github.ref == 'refs/heads/main'
              uses: actions/upload-artifact@v3
              with:
                  name: react-github-actions-build
                  path: |
                      ./
                      !node_modules
