name: Build and Test
on: [push]
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup NodeJs
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: Install client dependencies
              working-directory: ./
              run: yarn install
            - name: Client tests lint
              run: yarn run lint
            - name: Cypress run
              uses: cypress-io/github-action@v1
              with:
                  working-directory: ./
                  build: yarn run build
                  start: yarn run start
                  wait-on: http://localhost:3000
