name: Release

on:
    workflow_call:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            # Download previously shared build
            - name: Get artifact
              uses: actions/download-artifact@v1
              with:
                  name: react-github-actions-build
            - name: publish release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  prerelease: true
                  title: "Development Build"
                  files: |
                      react-github-actions-build
