name: Release

on:
    workflow_call:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            # Download previously shared build
            - name: Get artifact
              uses: actions/download-artifact@v1
              with:
                  name: react-github-actions-build
            # Zip the build using external action
            - name: Zip build
              uses: thedoctor0/zip-release@master
              with:
                  filename: react-github-actions-release-build.zip
                  path: react-github-actions-build
            # Upload as an artifact of the current workflow
            - name: Upload build zip artifact
              uses: actions/upload-artifact@v1
              with:
                  name: react-github-actions-release-build.zip
                  path: react-github-actions-release-build.zip
